### ISSUE TITLE
Remove ACCESS_KEY and SECRET_KEY from application.py!  Move them into config.py

### ISSUE THREAD

**Issue by jasonharrison** [catshark9/Open-Credit-Card-App-#1]
There are robots that actively search the internet for passwords/keys left in code and do nefarious things with them.  Plus, hard-coded configuration variables is bad practice.

If you'd like, I'll fix this for you with a pull request.

**Comment by filippovitale** [comment]
Looks like the `ACCESS_KEY` and `SECRET_KEY` are now invalid:

> The security token included in the request is invalid.

**Comment by jasonharrison** [comment]
@filippovitale Good.  I'll create a pull request shortly to move those variables to a configuration file.

**Comment by catshark9** [comment]
Awesome! Thanks! I created JSON dump at http://credit-cards.98he2uhpu4.us-east-2.elasticbeanstalk.com/CurrentCards/CurrentValue that will retrieve all the needed data. I'll update the code soon to reflect the API instead of dynamo

**Comment by jasonharrison** [comment]
Test comment, please ignore

_Sent from my Motorola XT1635-02 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jasonharrison** [comment]
Testing again, sorry if anyone sees this.  I'm trying to remove an annoying signature from my app.

**Comment by jasonharrison** [comment]
@catshark9 Did you want me to do a pull request and make the changes to the config/JSON?  Or were you going to do it?

**Comment by catshark9** [comment]
I don't think you need to anymore. I took out the dynamoDB code and replaced it with that api. I figured that would be easiest since it really isn't that necessary to have write privileges. Hopefully now, it should be simple to get it up and running locally
